# mpd/mpd.conf
# @author nate zhou
# @since 2023,2024,2025,2026

include "outputs.conf"

bind_to_address "127.0.0.1"
port "6600"

auto_update "yes"
restore_paused "yes"

music_directory "/home/xi/Music"
playlist_directory "/home/xi/.config/mpd/playlists"
db_file "/home/xi/.config/mpd/database"
log_file "/home/xi/.config/mpd/log"
pid_file "/home/xi/.config/mpd/pid"
state_file "/home/xi/.config/mpd/state"
