#!/bin/sh

# This script does the following:
#	Run by itself, set the wallpaper (at X start and Swaywm start).
#	If given a file, set that as the new wallpaper.
#	If given a directory, choose random file in it.

# Location of link to wallpaper link and default directory.
wp_dir=~/Pictures/Wallpapers
wallpaper="$HOME/Pictures/Wallpapers/default.png"

[ -f "$1" ] && ln -sf "$(readlink -f "$1")" "$wallpaper"  && notify-send -i "$wallpaper" "Wallpaper changed."

[ -d "$1" ] && ln -sf "$(find "$(readlink -f "$1")" -iregex '.*.\(jpg\|jpeg\|png\|gif\)' -type f | shuf -n 1)" "$wallpaper" && notify-send -i "$wallpaper" "Random Wallpaper chosen."

[ -z "$1" ] && [ -d "$wp_dir" ] && ln -sf "$(find "$(readlink -f "$wp_dir")" -iregex '.*.\(jpg\|jpeg\|png\|gif\)' -type f | shuf -n 1)" "$wallpaper" && notify-send -i "$wallpaper" "Random Wallpaper chosen."


if [ -z "$WAYLAND_DISPLAY" ]; then
    xwallpaper --zoom "$wallpaper"
else
    awww img "$wallpaper" --transition-type any
fi
